name: Client-lint
on:
  push:
    branches:
      - "**"
    paths:
      - "client/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies and lint
        working-directory: ./client
        run: |
          npm install
          npm run lint
