name: Server-lint
on:
  push:
    branches:
      - "**"
    paths:
      - "server/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies and run lint
        working-directory: ./server
        run: |
          npm install
          npm run lint
